# Generated by Django 5.2.6 on 2025-10-19 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether record is active')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Timestamp when record was activated', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deactivated', null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user_id', models.CharField(max_length=255)),
                ('expires_in', models.IntegerField()),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('last_token_refresh', models.DateTimeField(auto_now=True)),
                ('webhook_id', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Mercado Pago Integration',
                'verbose_name_plural': 'Mercado Pago Integrations',
                'db_table': 'mercadopago_integrations',
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('requires_invoice', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_rfc', models.CharField(blank=True, max_length=13)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('mp_preference_id', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
                'db_table': 'payment_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID in external system', max_length=255)),
                ('external_system', models.CharField(blank=True, help_text='Name of external system', max_length=50)),
                ('mp_payment_id', models.CharField(help_text='Legacy field - use external_id', max_length=255, unique=True)),
                ('mp_preference_id', models.CharField(max_length=255)),
                ('mp_collection_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('payer_email', models.EmailField(max_length=254)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('billing_rfc', models.CharField(blank=True, max_length=13)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_postal_code', models.CharField(blank=True, max_length=10)),
                ('billing_cfdi_use', models.CharField(default='G03', max_length=10)),
                ('billing_data_provided', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('authorized', 'Authorized'), ('in_process', 'In Process'), ('in_mediation', 'In Mediation'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('charged_back', 'Charged Back')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mp_created_at', models.DateTimeField(blank=True, null=True)),
                ('mp_updated_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='invoicing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentlink')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('click_type', models.CharField(choices=[('pay_button', 'Pay Button'), ('copy_link', 'Copy Link'), ('share', 'Share')], default='pay_button', max_length=20)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='payments.paymentlink')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Link Click',
                'verbose_name_plural': 'Payment Link Clicks',
                'db_table': 'payment_link_clicks',
                'indexes': [models.Index(fields=['payment_link', 'created_at'], name='payment_lin_payment_c60ee4_idx'), models.Index(fields=['tenant', 'created_at'], name='payment_lin_tenant__357b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('expiry_24h', '24 hours before expiry'), ('expiry_1h', '1 hour before expiry'), ('manual', 'Manual reminder')], default='manual', max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_reminders', to='core.notification')),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='payments.paymentlink')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Link Reminder',
                'verbose_name_plural': 'Payment Link Reminders',
                'db_table': 'payment_link_reminders',
                'indexes': [models.Index(fields=['payment_link', 'created_at'], name='payment_lin_payment_dcb656_idx'), models.Index(fields=['tenant', 'created_at'], name='payment_lin_tenant__977209_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='payments.paymentlink')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Link View',
                'verbose_name_plural': 'Payment Link Views',
                'db_table': 'payment_link_views',
                'indexes': [models.Index(fields=['payment_link', 'created_at'], name='payment_lin_payment_56c1dc_idx'), models.Index(fields=['tenant', 'created_at'], name='payment_lin_tenant__1b4898_idx')],
            },
        ),
    ]
