# Generated by Django 5.2.6 on 2025-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_fiscal_regime_choices'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='notification_count',
            field=models.IntegerField(default=0, help_text='Total de notificaciones enviadas para este link'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar notificaciones automáticas para este link', verbose_name='Enviar notificaciones'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='notify_on_create',
            field=models.BooleanField(default=True, help_text='Enviar notificación al cliente cuando se crea el link', verbose_name='Notificar al crear'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='notify_on_create_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email y WhatsApp')], default='email', max_length=20, verbose_name='Canal para notificación de creación'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='notify_on_expiry',
            field=models.BooleanField(default=False, help_text='Enviar email si link expira sin pagar', verbose_name='Notificar si expira'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='reminder_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email y WhatsApp')], default='email', max_length=20, verbose_name='Canal para recordatorios'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='reminder_hours_before',
            field=models.IntegerField(choices=[(6, '6 horas antes'), (12, '12 horas antes'), (24, '24 horas antes'), (48, '48 horas antes'), (72, '72 horas antes')], default=24, verbose_name='Anticipación del recordatorio'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag para tracking si ya se envió recordatorio'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='send_reminders',
            field=models.BooleanField(default=True, help_text='Recordatorio automático antes de expirar', verbose_name='Enviar recordatorios'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['status', 'send_reminders', 'reminder_sent', 'expires_at'], name='idx_link_reminders'),
        ),
    ]
