# Generated by Django 5.2.6 on 2025-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_notification_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='notify_on_create_channel',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='reminder_channel',
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='notification_count',
            field=models.IntegerField(default=0, help_text='Total de notificaciones por email enviadas para este link'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar notificaciones automáticas por email para este link', verbose_name='Enviar notificaciones'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='notify_on_create',
            field=models.BooleanField(default=True, help_text='Enviar email al cliente cuando se crea el link', verbose_name='Notificar al crear'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='send_reminders',
            field=models.BooleanField(default=True, help_text='Recordatorio automático por email antes de expirar', verbose_name='Enviar recordatorios'),
        ),
    ]
