# Generated by Django 5.2.6 on 2025-11-15 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_channel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('paid_other_method', 'Cliente pagó por otro medio'), ('wrong_amount', 'Error en monto o descripción'), ('customer_request', 'Cliente solicitó cancelación'), ('duplicate', 'Link duplicado'), ('expired_intent', 'Cliente ya no quiere pagar'), ('other', 'Otra razón'), ('not_specified', 'No especificada')], help_text='Reason for cancellation', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when link was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled the link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payment_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
