# Generated by Django 5.2.6 on 2025-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mp_payment_id',
            field=models.CharField(db_index=True, help_text='MercadoPago payment ID - indexed for webhook lookups', max_length=255, unique=True),
        ),
    ]
