# Generated by Django 5.2.6 on 2025-10-19 22:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('plan_name', models.CharField(default='Kita Pro', help_text='Name of the subscription plan', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('299.00'), help_text='Monthly price in currency', max_digits=8)),
                ('currency', models.CharField(default='MXN', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='trial', help_text='Current subscription status', max_length=20)),
                ('trial_started_at', models.DateTimeField(auto_now_add=True, help_text='When trial period started')),
                ('trial_ends_at', models.DateTimeField(db_index=True, help_text='When trial period ends')),
                ('current_period_start', models.DateTimeField(blank=True, db_index=True, help_text='Start of current billing period', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, help_text='End of current billing period', null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, db_index=True, help_text='Next scheduled billing date', null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date of last successful payment', null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of last payment', max_digits=8, null=True)),
                ('failed_payment_attempts', models.IntegerField(default=0, help_text='Number of consecutive failed payment attempts')),
                ('last_failed_payment_date', models.DateTimeField(blank=True, help_text='Date of last failed payment attempt', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When subscription was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancel at end of current period instead of immediately')),
                ('mp_subscription_id', models.CharField(blank=True, db_index=True, help_text='MercadoPago subscription identifier', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID in external system', max_length=255)),
                ('external_system', models.CharField(blank=True, help_text='Name of external system', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=8)),
                ('currency', models.CharField(default='MXN', help_text='Currency code (ISO 4217)', max_length=3)),
                ('payment_method', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('stripe', 'Stripe'), ('transfer', 'Transfer'), ('cash', 'Cash')], db_index=True, default='mercadopago', help_text='Payment method used', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Payment status', max_length=20)),
                ('external_payment_id', models.CharField(blank=True, db_index=True, help_text='External payment system ID', max_length=255)),
                ('external_payment_data', models.JSONField(blank=True, default=dict, help_text='Raw data from payment provider')),
                ('billing_period_start', models.DateTimeField(help_text='Start of billing period')),
                ('billing_period_end', models.DateTimeField(help_text='End of billing period')),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, help_text='When payment was processed', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts allowed')),
                ('invoice_generated', models.BooleanField(default=False, help_text='Whether invoice was generated')),
                ('invoice_sent', models.BooleanField(default=False, help_text='Whether invoice was sent')),
                ('invoice_data', models.JSONField(blank=True, default=dict, help_text='Invoice generation data')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('subscription', models.ForeignKey(help_text='Associated subscription', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Billing Payment',
                'verbose_name_plural': 'Billing Payments',
                'db_table': 'billing_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'status'], name='idx_sub_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'next_billing_date'], name='idx_sub_status_billing'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['trial_ends_at', 'status'], name='idx_sub_trial_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', '-created_at'], name='idx_sub_status_created'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_tenant_subscription'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['tenant', '-created_at'], name='idx_pay_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['subscription', '-created_at'], name='idx_pay_sub_created'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['status', 'processed_at'], name='idx_pay_status_processed'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['external_payment_id'], name='idx_pay_external_id'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['status', 'retry_count'], name='idx_pay_status_retry'),
        ),
    ]
