# Generated by Django 5.2.6 on 2025-10-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(db_index=True, max_length=5)),
                ('asentamiento', models.CharField(max_length=255)),
                ('tipo_asentamiento', models.CharField(max_length=100)),
                ('municipio', models.CharField(db_index=True, max_length=255)),
                ('estado', models.CharField(db_index=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=255)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código Postal',
                'verbose_name_plural': 'Códigos Postales',
                'db_table': 'codigos_postales',
                'indexes': [models.Index(fields=['codigo_postal', 'asentamiento'], name='idx_cp_colonia'), models.Index(fields=['municipio'], name='idx_municipio'), models.Index(fields=['estado'], name='idx_estado')],
                'unique_together': {('codigo_postal', 'asentamiento')},
            },
        ),
    ]
