# Generated by Django 5.2.6 on 2025-10-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_codigopostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='calle',
            field=models.CharField(max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='codigo_postal',
            field=models.CharField(db_index=True, max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='colonia',
            field=models.CharField(max_length=255, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='estado',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='fiscal_regime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='municipio',
            field=models.CharField(max_length=255, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='numero_exterior',
            field=models.CharField(max_length=20, verbose_name='Número Exterior'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rfc',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
