# Generated by Django 5.2.6 on 2025-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_tenant_field_validations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='fiscal_regime',
            field=models.CharField(choices=[('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('626', '626 - Régimen Simplificado de Confianza (RESICO)'), ('621', '621 - Incorporación Fiscal'), ('606', '606 - Arrendamiento'), ('605', '605 - Sueldos y Salarios'), ('615', '615 - Régimen de los ingresos por obtención de premios')], help_text='Régimen fiscal del SAT para personas físicas', max_length=10),
        ),
    ]
