# Generated by Django 5.2.6 on 2025-11-14 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_fiscal_regime_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='postmark_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='MessageID de Postmark para tracking de email', max_length=100),
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(db_index=True, help_text='MessageID de Postmark (UUID)', max_length=100, unique=True)),
                ('message_stream', models.CharField(default='outbound', help_text='Stream de Postmark', max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, db_index=True, help_text="Tag de Postmark (ej: 'link_created')", max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata enviada en el email')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened', models.BooleanField(db_index=True, default=False)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('clicked', models.BooleanField(default=False)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('bounced', models.BooleanField(db_index=True, default=False)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_type', models.CharField(blank=True, max_length=50)),
                ('bounce_description', models.TextField(blank=True)),
                ('spam_complaint', models.BooleanField(default=False)),
                ('spam_complaint_at', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('client_os', models.CharField(blank=True, max_length=100)),
                ('client_platform', models.CharField(blank=True, max_length=50)),
                ('geo_country', models.CharField(blank=True, max_length=100)),
                ('geo_city', models.CharField(blank=True, max_length=100)),
                ('geo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('postmark_bounce_id', models.BigIntegerField(blank=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('spam', 'Spam Complaint')], db_index=True, default='sent', max_length=20)),
                ('notification', models.ForeignKey(blank=True, help_text='Notificación asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='core.notification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'db_table': 'email_events',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['message_id'], name='idx_email_message_id'), models.Index(fields=['notification', 'status'], name='idx_email_notif_status'), models.Index(fields=['tag', '-sent_at'], name='idx_email_tag_date'), models.Index(fields=['recipient', '-sent_at'], name='idx_email_recipient')],
            },
        ),
    ]
