# Generated by Django 5.2.6 on 2025-11-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_email_event_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Context variables for HTML email templates'),
        ),
    ]
