# Generated by Django 5.2.6 on 2025-11-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_metadata_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pac_integration_data',
            field=models.JSONField(blank=True, default=dict, help_text='Integration data for PAC providers (organization IDs, Live Keys, timestamps)', verbose_name='PAC Integration Data'),
        ),
    ]
