# Generated by Django 5.2.6 on 2025-10-19 22:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary email for authentication and notifications', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(db_index=True, help_text="User's first name", max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(db_index=True, help_text="User's last name", max_length=150, verbose_name='last name')),
                ('username', models.CharField(blank=True, help_text='Legacy field, not used for auth', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone in E.164 format for WhatsApp', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone must be in E.164 format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('is_email_verified', models.BooleanField(db_index=True, default=False, help_text='Whether email has been verified')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of email verification', null=True)),
                ('onboarding_completed', models.BooleanField(db_index=True, default=False, help_text='Whether user completed onboarding')),
                ('onboarding_step', models.PositiveSmallIntegerField(choices=[(1, 'Identidad del Negocio'), (2, 'Conectar MercadoPago'), (3, 'Datos Fiscales y CSD'), (4, 'Suscripción')], default=1, help_text='Current step in onboarding flow')),
                ('terms_accepted_at', models.DateTimeField(blank=True, help_text='When user accepted terms', null=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, help_text='When user accepted privacy policy', null=True)),
                ('accepts_marketing', models.BooleanField(db_index=True, default=False, help_text='Opted in for marketing')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text='Short biography', max_length=500)),
                ('location', models.CharField(blank=True, db_index=True, help_text='User location', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Personal website')),
                ('timezone', models.CharField(choices=[('America/Mexico_City', 'Ciudad de México (GMT-6)'), ('America/Tijuana', 'Tijuana (GMT-8)'), ('America/Monterrey', 'Monterrey (GMT-6)'), ('America/Cancun', 'Cancún (GMT-5)'), ('America/Hermosillo', 'Hermosillo (GMT-7)'), ('America/Mazatlan', 'Mazatlán (GMT-7)'), ('America/Chihuahua', 'Chihuahua (GMT-6)'), ('America/Merida', 'Mérida (GMT-6)')], db_index=True, default='America/Mexico_City', help_text='Preferred timezone', max_length=50)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Preferred language', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='auto', help_text='UI theme preference', max_length=10)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('whatsapp_notifications', models.BooleanField(default=True, help_text='Receive WhatsApp notifications')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, help_text='Last recorded activity')),
                ('login_count', models.PositiveIntegerField(default=0, help_text='Total logins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address')),
                ('user_agent', models.TextField(help_text='Browser user agent')),
                ('device_type', models.CharField(choices=[('desktop', 'Escritorio'), ('mobile', 'Móvil'), ('tablet', 'Tableta'), ('unknown', 'Desconocido')], default='unknown', help_text='Type of device', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser name', max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, help_text='Country from IP', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City from IP', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Session expiration')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Session validity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='idx_user_email_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['onboarding_completed', '-date_joined'], name='idx_user_onboard_date'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['accepts_marketing', 'is_active'], name='idx_user_marketing'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified', '-date_joined'], name='idx_user_verified'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-last_activity'], name='idx_profile_activity'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['timezone', 'email_notifications'], name='idx_profile_tz_email'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active', '-last_activity'], name='idx_session_user_active'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at', 'is_active'], name='idx_session_expires'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address', 'created_at'], name='idx_session_ip_created'),
        ),
    ]
