# Generated by Django 5.2.6 on 2025-10-19 22:55

import core.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_file', models.FileField(blank=True, max_length=500, null=True, storage=core.storage.get_tenant_csd_storage, upload_to='csd/certificates/')),
                ('private_key_file', models.FileField(blank=True, max_length=500, null=True, storage=core.storage.get_tenant_csd_storage, upload_to='csd/private_keys/')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('issuer_name', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('encrypted_certificate', models.TextField()),
                ('encrypted_private_key', models.TextField()),
                ('encrypted_password', models.TextField()),
                ('encryption_key_id', models.CharField(max_length=255)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_error', models.TextField(blank=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('sw_uploaded', models.BooleanField(default=False)),
                ('sw_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('sw_response', models.JSONField(blank=True, default=dict)),
                ('sw_error', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'CSD Certificate',
                'verbose_name_plural': 'CSD Certificates',
                'db_table': 'csd_certificates',
                'indexes': [models.Index(fields=['tenant', 'is_active', 'valid_to'], name='csd_certifi_tenant__40e841_idx'), models.Index(fields=['serial_number'], name='csd_certifi_serial__c35806_idx'), models.Index(fields=['tenant', 'sw_uploaded'], name='csd_certifi_tenant__ddf12c_idx'), models.Index(fields=['valid_to'], name='csd_certifi_valid_t_97caaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, storage=core.storage.get_tenant_csd_storage, upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('upload_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('upload_session', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='uploaded', max_length=20)),
                ('file_type', models.CharField(choices=[('csd_certificate', 'CSD Certificate'), ('csd_private_key', 'CSD Private Key'), ('invoice_xml', 'Invoice XML'), ('invoice_pdf', 'Invoice PDF'), ('document', 'Document'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'db_table': 'file_uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='file_upload_tenant__af8e6e_idx'), models.Index(fields=['upload_token'], name='file_upload_upload__c20da3_idx'), models.Index(fields=['tenant', 'file_type', 'status'], name='file_upload_tenant__8fd67c_idx'), models.Index(fields=['upload_session', 'status'], name='file_upload_upload__814275_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('folio', models.CharField(max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_rfc', models.CharField(max_length=13)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('payment_method', models.CharField(default='PUE', max_length=10)),
                ('payment_form', models.CharField(default='03', max_length=10)),
                ('cfdi_use', models.CharField(default='G03', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('stamped', 'Stamped'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='draft', max_length=20)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='invoices/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('stamped_at', models.DateTimeField(blank=True, null=True)),
                ('pac_response', models.JSONField(blank=True, default=dict)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='invoices_tenant__14414f_idx'), models.Index(fields=['customer_rfc'], name='invoices_custome_6f17d1_idx'), models.Index(fields=['uuid'], name='invoices_uuid_4abd68_idx'), models.Index(fields=['tenant', 'created_at'], name='invoices_tenant__e4fc29_idx'), models.Index(fields=['stamped_at'], name='invoices_stamped_d0fefa_idx'), models.Index(fields=['tenant', 'serie', 'folio'], name='invoices_tenant__aca497_idx')],
                'unique_together': {('tenant', 'serie', 'folio')},
            },
        ),
    ]
